server:
  port: 8328

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: lys
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none # none create
    properties:
      hibernate:
        "[default_batch_fetch_size]": 500
        "[show_sql]": true # sout에 어떤 sql 실행되는거 보여줌
        "[format_sql]": true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.yspjt.dbafe.Model
